2023-03-20 10:57:26,016 WARNING Not Found: /cart.json
2023-03-20 10:57:28,892 WARNING Not Found: /cart.json
2023-03-20 10:57:45,704 WARNING New Product add notification failed to sync
2023-03-20 10:57:47,108 WARNING Not Found: /cart.json
2023-03-21 10:05:09,238 WARNING Not Found: /cart.json
2023-03-21 10:05:09,771 WARNING Not Found: /cart.json
2023-03-21 10:05:16,300 WARNING Not Found: /cart.json
2023-03-21 10:05:49,046 WARNING Not Found: /cart.json
2023-03-21 10:05:56,399 WARNING Not Found: /cart.json
2023-03-21 10:06:09,657 WARNING Not Found: /cart.json
2023-03-21 10:06:12,765 WARNING Not Found: /cart.json
2023-03-21 10:06:22,890 WARNING Not Found: /cart.json
2023-03-21 10:06:29,015 WARNING Not Found: /cart.json
2023-03-21 10:06:31,157 WARNING Not Found: /cart.json
2023-03-21 10:06:33,195 WARNING Not Found: /cart.json
2023-03-21 10:06:34,981 WARNING Not Found: /cart.json
2023-03-21 10:07:22,366 WARNING Not Found: /cart.json
2023-03-21 10:07:37,710 WARNING Not Found: /cart.json
2023-03-21 10:07:54,334 WARNING New Product add notification failed to sync
2023-03-21 10:07:57,954 WARNING Not Found: /cart.json
2023-03-21 10:08:42,859 WARNING New Product add notification failed to sync
2023-03-21 10:08:46,868 WARNING Not Found: /cart.json
2023-03-21 10:27:36,685 WARNING Not Found: /cart.json
2023-03-21 10:27:46,765 WARNING New Product add notification failed to sync
2023-03-21 10:27:50,715 WARNING Not Found: /cart.json
2023-03-21 10:38:50,838 WARNING Not Found: /cart.json
2023-03-21 10:38:54,203 WARNING Not Found: /cart.json
2023-03-21 10:38:56,801 WARNING Not Found: /cart.json
2023-03-21 10:39:03,674 WARNING Not Found: /cart.json
2023-03-21 10:39:11,551 WARNING Not Found: /cart.json
2023-03-21 10:39:35,088 WARNING Not Found: /cart.json
2023-03-21 10:52:21,097 WARNING Not Found: /cart.json
2023-03-21 10:54:37,192 WARNING Not Found: /cart.json
2023-03-21 10:56:49,748 ERROR Internal Server Error: /sales
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Desktop\smartmgr.com\imsApp\auth.py", line 8, in wrapper_function
    return view_function(request,*args,**kwargs)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\smartmgr.com\imsApp\views.py", line 630, in sales_mgt
    return render(request,'sales.html', context)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\template\base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '  product.stock' from 'product  product.stock'
2023-03-21 10:56:52,752 WARNING Not Found: /cart.json
2023-03-21 10:59:05,436 WARNING Not Found: /cart.json
2023-03-21 11:01:37,975 WARNING Not Found: /cart.json
2023-03-21 11:04:33,228 WARNING Not Found: /cart.json
2023-03-21 11:05:05,777 WARNING Not Found: /cart.json
2023-03-21 11:05:26,348 WARNING Not Found: /cart.json
2023-03-21 11:05:29,591 WARNING Not Found: /cart.json
2023-03-21 11:05:35,090 WARNING Not Found: /cart.json
2023-03-21 11:05:49,425 WARNING Not Found: /cart.json
2023-03-21 11:05:54,993 WARNING Not Found: /cart.json
2023-03-21 11:05:58,301 WARNING Not Found: /cart.json
2023-03-21 11:07:09,805 WARNING Not Found: /cart.json
2023-03-21 11:07:10,968 WARNING Not Found: /cart.json
2023-03-21 11:07:11,676 WARNING Not Found: /cart.json
2023-03-21 11:07:13,897 WARNING Not Found: /cart.json
2023-03-21 11:07:15,390 WARNING Not Found: /cart.json
2023-03-21 11:07:17,022 WARNING Not Found: /cart.json
2023-03-21 11:17:54,420 WARNING Not Found: /cart.json
2023-03-21 11:17:55,200 WARNING Not Found: /cart.json
2023-03-21 11:18:12,853 WARNING Not Found: /cart.json
2023-03-21 11:26:09,814 WARNING Not Found: /cart.json
2023-03-21 11:26:19,065 WARNING Not Found: /cart.json
2023-03-21 11:26:23,433 WARNING Not Found: /cart.json
2023-03-21 11:26:26,465 WARNING Not Found: /cart.json
2023-03-21 11:26:35,355 WARNING Not Found: /cart.json
2023-03-21 11:26:40,627 WARNING Not Found: /cart.json
2023-03-21 11:27:00,603 WARNING Not Found: /cart.json
2023-03-21 11:27:06,197 WARNING Not Found: /cart.json
2023-03-21 11:27:08,117 WARNING Not Found: /cart.json
2023-03-21 11:27:09,983 WARNING Not Found: /cart.json
2023-03-21 11:27:12,593 WARNING Not Found: /cart.json
2023-03-21 11:27:20,116 WARNING Not Found: /cart.json
2023-03-21 11:27:23,391 WARNING Not Found: /cart.json
2023-03-21 11:27:36,560 WARNING Not Found: /cart.json
2023-03-21 11:27:43,713 WARNING Not Found: /cart.json
2023-03-21 11:27:46,648 WARNING Not Found: /cart.json
2023-03-22 10:32:24,834 WARNING Not Found: /cart.json
2023-03-22 10:32:29,190 WARNING Not Found: /cart.json
2023-03-22 10:32:36,420 WARNING Not Found: /cart.json
2023-03-22 10:32:40,611 WARNING Not Found: /cart.json
2023-03-22 10:33:28,286 WARNING Not Found: /cart.json
2023-03-22 10:33:33,694 WARNING Not Found: /cart.json
2023-03-22 10:33:43,076 WARNING Not Found: /cart.json
2023-03-22 10:33:48,825 WARNING Not Found: /cart.json
2023-03-22 10:33:52,439 WARNING Not Found: /cart.json
2023-03-22 10:36:41,702 WARNING Not Found: /cart.json
2023-03-22 10:36:48,213 WARNING Not Found: /cart.json
2023-03-22 10:36:50,685 WARNING Not Found: /cart.json
2023-03-22 10:37:33,756 WARNING Not Found: /cart.json
2023-03-22 10:37:38,569 WARNING Not Found: /cart.json
2023-03-22 10:37:52,252 WARNING New Product add notification failed to sync
2023-03-22 10:37:53,635 WARNING Not Found: /cart.json
2023-03-22 11:00:40,178 ERROR Internal Server Error: /store/manage/6/addP
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\smartmgr.com\imsApp\views.py", line 538, in addProductStore
    print(detal)
NameError: name 'detal' is not defined
2023-03-22 11:02:12,525 WARNING Not Found: /cart.json
2023-03-22 11:02:27,141 ERROR Internal Server Error: /store/manage/6/addP
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Downloads\ims_django_0\ims_django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\smartmgr.com\imsApp\views.py", line 538, in addProductStore
    print(detal)
NameError: name 'detal' is not defined
2023-03-22 11:03:19,518 WARNING Not Found: /cart.json
2023-03-22 11:03:48,130 WARNING New Product add notification failed to sync
2023-03-22 11:03:51,242 WARNING Not Found: /cart.json
2023-03-22 11:04:41,757 WARNING Not Found: /cart.json
2023-03-22 11:04:54,169 WARNING Not Found: /cart.json
2023-03-22 11:04:58,096 WARNING Not Found: /cart.json
2023-03-22 11:05:06,931 WARNING Not Found: /cart.json
2023-03-22 11:05:11,987 WARNING Not Found: /cart.json
2023-03-22 11:05:25,991 WARNING Not Found: /cart.json
2023-03-22 11:05:29,868 WARNING Not Found: /cart.json
2023-03-22 11:05:34,615 WARNING Not Found: /cart.json
2023-03-22 11:05:43,373 WARNING Not Found: /cart.json
2023-03-22 11:05:52,246 WARNING Not Found: /cart.json
2023-03-23 11:29:15,068 WARNING Not Found: /cart.json
2023-03-23 11:33:13,058 WARNING Not Found: /cart.json
2023-03-23 11:33:19,470 WARNING Not Found: /cart.json
2023-03-23 11:33:26,118 WARNING Not Found: /cart.json
2023-03-23 11:41:22,631 WARNING Not Found: /cart.json
2023-03-23 11:45:14,960 WARNING Not Found: /cart.json
2023-03-23 11:45:33,149 WARNING Not Found: /cart.json
2023-03-25 09:41:55,043 WARNING Not Found: /cart.json
2023-03-25 09:41:56,820 WARNING Not Found: /cart.json
2023-03-25 09:42:07,724 WARNING Not Found: /cart.json
2023-03-25 09:42:11,509 WARNING Not Found: /cart.json
2023-03-25 09:42:20,788 WARNING Not Found: /cart.json
2023-03-25 09:42:26,318 WARNING Not Found: /cart.json
2023-03-25 09:42:43,252 WARNING Not Found: /cart.json
2023-03-25 09:42:56,624 WARNING Not Found: /cart.json
2023-03-25 09:43:03,132 WARNING Not Found: /cart.json
2023-03-25 09:43:07,198 WARNING Not Found: /cart.json
2023-03-25 09:43:09,321 WARNING Not Found: /cart.json
2023-03-25 09:43:11,494 WARNING Not Found: /cart.json
2023-03-25 09:43:13,554 WARNING Not Found: /cart.json
2023-03-25 09:43:28,943 WARNING Not Found: /cart.json
2023-03-25 09:43:34,236 WARNING Not Found: /cart.json
2023-03-25 09:43:37,038 WARNING Not Found: /cart.json
2023-03-25 09:43:38,678 WARNING Not Found: /cart.json
2023-03-25 09:43:40,524 WARNING Not Found: /cart.json
2023-03-25 09:43:45,827 WARNING Not Found: /cart.json
2023-03-25 09:45:16,799 WARNING Not Found: /cart.json
2023-03-25 09:45:19,764 WARNING Not Found: /cart.json
2023-03-25 09:56:31,251 WARNING Not Found: /cart.json
2023-03-25 09:56:35,953 WARNING Not Found: /cart.json
2023-03-25 09:56:41,946 WARNING Not Found: /cart.json
2023-03-25 09:56:46,997 WARNING Not Found: /cart.json
2023-03-25 09:56:57,688 WARNING Not Found: /cart.json
2023-03-25 09:57:04,326 WARNING Not Found: /cart.json
2023-03-25 09:57:08,948 WARNING Not Found: /cart.json
2023-03-25 09:57:11,478 WARNING Not Found: /cart.json
2023-03-25 09:57:21,892 WARNING Not Found: /cart.json
2023-03-25 09:57:25,082 WARNING Not Found: /cart.json
2023-03-25 09:57:34,308 WARNING Not Found: /cart.json
2023-03-25 09:57:38,882 WARNING Not Found: /cart.json
2023-03-25 09:57:44,538 WARNING Not Found: /cart.json
2023-03-25 09:57:49,509 WARNING Not Found: /cart.json
2023-03-25 09:57:51,824 WARNING Not Found: /cart.json
2023-04-04 09:48:48,857 ERROR Internal Server Error: /delete_product
Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 187, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\models.py", line 148, in delete_stock
    stock = Stock.objects.get(id=instance.stock.id).delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 205, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 168, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
imsApp.models.Stock.DoesNotExist: Stock matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 187, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\views.py", line 434, in delete_product
    product.delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\base.py", line 1094, in delete
    return collector.delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\deletion.py", line 488, in delete
    signals.post_delete.send(
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\models.py", line 150, in delete_stock
    return instance.stock.id
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 205, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 168, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
imsApp.models.Stock.DoesNotExist: Stock matching query does not exist.
2023-04-04 09:59:23,411 ERROR Internal Server Error: /delete_product
Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 187, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\models.py", line 150, in delete_stock
    stock = Stock.objects.get(id=instance.stock.id).delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 205, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 168, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
imsApp.models.Stock.DoesNotExist: Stock matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 187, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'stock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\views.py", line 434, in delete_product
    product.delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\base.py", line 1094, in delete
    return collector.delete()
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\deletion.py", line 488, in delete
    signals.post_delete.send(
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\imsApp\models.py", line 152, in delete_stock
    return instance.stock.id
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 205, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 168, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "C:\Users\thesm\OneDrive\Desktop\smartmgr.com\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
imsApp.models.Stock.DoesNotExist: Stock matching query does not exist.
2023-04-04 10:07:47,062 WARNING Failed to sync notifications for stock
2023-04-04 10:08:07,623 WARNING Failed to sync notifications for stock
2023-04-04 10:09:06,421 WARNING New Product add notification failed to sync
2023-04-04 10:39:36,276 WARNING Failed to sync notifications for stock
